use enkelibrary ; 
INSERT INTO genre (genName, genDesc) VALUES
('Action', 'Exciting and fast-paced genre filled with thrilling adventures.'),
('Adventure', 'Journey to unknown lands and explore the great unknown.'),
('Mystery', 'Unravel intriguing puzzles and solve mysterious cases.'),
('Romance', 'Heartwarming tales of love and relationships.'),
('Fantasy', 'Escape to magical worlds with mythical creatures.'),
('Science Fiction', 'Explore the possibilities of future technology and space travel.'),
('Thriller', 'Keep you on the edge of your seat with suspenseful plots.'),
('Horror', 'Experience the chilling and terrifying side of storytelling.'),
('Comedy', 'Laugh out loud with humorous and witty narratives.'),
('Drama', 'Deep and emotional stories that tug at your heartstrings.'),
('Historical', 'Revisit the past through rich and immersive historical narratives.'),
('Crime', 'Dive into the gritty world of crime, detectives, and criminals.'),
('Biography', 'Discover the fascinating lives of real people.'),
('Music', 'Celebrate the power of music and its impact on lives.'),
('Documentary', 'Informative and eye-opening explorations of real-life subjects.'),
('Family', 'Perfect for all ages, fostering family values and bonds.'),
('Animation', 'Vibrant and imaginative worlds brought to life through animation.'),
('Science', 'Uncover the wonders of our natural world and scientific discoveries.'),
('War', 'Explore the hardships and heroism of wartime scenarios.'),
('Western', 'Experience the Old West and the cowboy way of life.'),
('Superhero', 'Join extraordinary characters with superhuman abilities.'),
('Romantic Comedy', 'Love stories with a humorous and light-hearted touch.'),
('Historical Fiction', 'Blend of history and fiction in captivating narratives.'),
('Time Travel', 'Journey through time and witness historical events.'),
('Post-Apocalyptic', 'Stories set in the aftermath of a global catastrophe.'),
('Space Opera', 'Epic adventures in the vastness of outer space.'),
('Cyberpunk', 'Futuristic worlds with advanced technology and cybernetics.'),
('Sports', 'Feel the excitement of sports and competition.'),
('Supernatural', 'Unearthly and paranormal occurrences take center stage.'),
('Alien Invasion', "Earth's struggle against extraterrestrial invaders."),
('Steampunk', 'Alternate history with steam-powered technology.'),
('Fantasy Romance', 'Romantic tales set in fantastical realms.'),
('Political Thriller', 'Intrigue and suspense in the political landscape.'),
('Slice of Life', 'Everyday life moments and human relationships.'),
('Espionage', 'Secret agents and covert operations in a web of deception.'),
('Apocalyptic', 'The world on the brink of collapse and survival.'),
('Coming of Age', 'The journey from adolescence to adulthood.'),
('Magical Realism', 'Blend of magic and reality in a seamless narrative.'),
('Gothic', 'Dark and mysterious tales with a touch of the supernatural.'),
('Comics', 'Bringing comic book heroes and stories to life.'),
('Classic Literature', 'Timeless literary works that have endured the ages.'),
('Legal Drama', 'Courtroom battles and legal dilemmas.'),
('Animation Fantasy', 'Fantasy worlds brought to life through animation.'),
('Musical', 'Storytelling through music and song.'),
('Fairy Tale', 'Timeless and enchanting fairy tale adventures.'),
('Urban Fantasy', 'Fantasy elements in a modern urban setting.'),
('Psychological Thriller', 'Exploring the depths of the human mind.'),
('Military', 'Military life, strategy, and wartime narratives.'),
('Medical Drama', 'Medical professionals and the challenges they face.'),
('Spy Fiction', 'Espionage, secret agents, and international intrigue.');